# Change these first
owner: Dcode-Studios # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: BanSync Website
    url: https://bansync.dcode.site

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dcode.site
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://bansync.dcode.site/assets/img/status_logo.png
  name: Service Status
  introTitle: "Status for the services of **Dcode Studios**."
  introMessage: This is the status page for our services such as the website and bot.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
